// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 16
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){


var za=this,Aa=function(){var a=YT.Player,b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},Ba=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Ca=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Da=function(a){if(null==a)return String(a);var b=Ca.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Ea=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},ma=function(a){if(!a||"object"!=Da(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Ea(a,"constructor")&&!Ea(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Ea(a,b)},Fa=function(a,b){var c=b||("array"==Da(a)?[]:{}),d;for(d in a)if(Ea(a,d)){var e=a[d];"array"==Da(e)?("array"!=Da(c[d])&&(c[d]=[]),c[d]=Fa(e,c[d])):ma(e)?(ma(c[d])||(c[d]={}),c[d]=Fa(e,c[d])):c[d]=e}return c};var qa=null,Ha=Math.random(),Ia=null,Ja=null,Ka={};var La,Ma,Na,Oa,Pa,Qa,Ra,Ta,Ua,Va,Wa,Xa,R,Ya,Za,$a,ab,bb,cb,db,eb,fb,gb,hb,jb,lb,mb,nb,ob,pb,qb,rb,sb,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Eb,Fb,Gb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,S,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,kd,ld,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,
ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te;
(function(){var a=function(a){return{toString:function(){return a}}};La=a("");Ma=a("");Na="";Oa=a("");Pa=a("");Qa=a("");Ra=a("");Ta=a("");Ua=a("");Va=a("");Wa=a("");Xa=a("0");R=a("1");Ya=a("");Za=a("");$a=a("");
ab=a("");bb=a("");cb=a("");db=a("");eb=a("");fb=a("");gb=a("");hb=a("");jb=a("");lb=a("");mb=a("");nb=a("");ob=a("");pb=
a("");qb=a("");rb=a("");sb=a("");tb=a("");ub=a("");vb=a("");wb=a("2");xb=a("");yb=a("");zb=a("");Ab=a("");Bb=a("");Cb=a("");Eb=a("");Fb=a("");Gb=a("");Ib=a("");
Jb=a("");Kb=a("");Lb=a("");Mb=a("");Nb=a("");Ob=a("");Pb=a("3");Qb=a("");Rb=a("");Sb=a("");Tb=a("");Ub=a("");Vb=a("");Wb=a("");Xb=a("4");Yb=a("");Zb=a("");
$b=a("");ac=a("");bc=a("");cc=a("");dc=a("");ec=a("");fc=a("");gc=a("");hc=a("");ic=a("");jc=a("");kc=a("");lc=a("");mc=a("");nc=a("");pc=a("");
qc=a("");rc=a("");sc=a("");tc=a("");uc=a("");vc=a("");wc=a("");xc=a("");yc=a("");zc=a("");Ac=a("5");Bc=a("");Cc=a("11");Dc=a("12");Ec=a("");Fc=a("");Gc=a("6");
S=a("");Hc=a("");Ic=a("");Jc=a("");Kc=a("");Lc=a("7");Mc=a("");Nc=a("");Oc=a("");Pc=a("");Qc=a("");Rc=a("");Sc=a("");Tc=a("");Uc=a("");Vc=a("");Wc=a("");Xc=a("");Yc=a("");Zc=
a("");$c=a("");ad=a("");bd=a("");cd=a("");dd=a("");ed=a("");fd=a("");gd=a("8");hd=a("");kd=a("");ld=a("");od=a("");pd=a("");qd=a("");rd=a("");sd=a("");td=a("");ud=a("");vd=a("");
wd=a("");xd=a("");yd=a("");zd=a("");Ad=a("");Bd=a("");Cd=a("");Dd=a("");Ed=a("");Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");
Pd=a("");Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");Vd=a("");Wd=a("");Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");
ee=a("10");fe=a("");ge=a("");he=a("");ie=a("");je=a("");ke=a("");le=a("");me=a("");ne=a("");oe=a("");pe=a("");qe=a("");re=a("");se=a("");te=a("");ue=a("");
ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");Ce="";De=a("");Ee=a("");Fe=a("");Ge=a("");He=a("");Ie=a("");Je=a("");Ke=a("");Le=a("");
Me=a("");Ne=a("");Oe=a("");Pe=a("");Qe=a("");Re=a("");Se=a("");Te=a("")})();var Ue=function(){},L=function(a){return"function"==typeof a},U=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},Ve=function(a){return"number"==Da(a)&&!isNaN(a)},We=function(a){return/^[0-9]+$/.test(a)},Xe=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},Ye=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},N=function(a){return Math.round(Number(a))||0},oa=function(a){return"false"==
String(a).toLowerCase()?!1:!!a},Ze=function(a){var b=[];if(U(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},K=function(){return new Date},$e=function(a,b){if(!Ve(a)||!Ve(b)||a>b)a=0,b=2147483647;return Math.round(Math.random()*(b-a)+a)},af=function(){this.prefix="gtm.";this.values={}};af.prototype.set=function(a,b){this.values[this.prefix+a]=b};af.prototype.get=function(a){return this.values[this.prefix+a]};af.prototype.contains=function(a){return void 0!==this.get(a)};
var bf=function(a,b,c){try{if(!a[ad])return a[Ac](a,b||Ue,c||Ue);c&&c()}catch(d){}return!1},cf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=Ye(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},df=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},ef=function(a){return function(){return a("GTM-NDJTNB")}},ff=function(a){for(var b=0;b<a.length;b++)a[b]()},ka=K().getTime(),na=function(a,
b,c){return a&&a.hasOwnProperty(b)?a[b]:c},gf=function(a,b,c){a.prototype["gtm_proxy_"+b]=a.prototype[b];a.prototype[b]=c},hf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},la=function(a,b,c){if(!(b&&c&&hf(a)&&U(a)&&0!=a.length))return null;for(var d={},e=0;e<a.length;e++)a[e]&&a[e].hasOwnProperty(b)&&a[e].hasOwnProperty(c)&&(d[a[e][b]]=a[e][c]);return d},jf=function(a,b){0==b?a.Na=!0:a.complete=!0;var c=a.g;a.i&&(a.i.ka[c]=b);Ka[c]&&(Ka[c].state=b)},kf=function(a,b){a.sort(function(a,
d){return b(a,d)?-1:b(d,a)?1:0})};var J=window,P=document,nf=navigator,I=function(a,b,c){var d=J[a];J[a]=void 0===d||c?b:d;return J[a]},O=function(a,b,c,d){return(d||"http:"!=J.location.protocol?a:b)+c},uf=function(a){var b=P.getElementsByTagName("script")[0]||P.body||P.head;b.parentNode.insertBefore(a,b)},pa=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},p=function(a,b,c){var d=P.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;pa(d,b);c&&(d.onerror=c);uf(d)},ha=function(a,b){var c=P.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";uf(c);pa(c,b);void 0!==a&&(c.src=a);return c},A=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},V=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},r=function(a){J.setTimeout(a,0)},sa=!1,
ua=[],vf=function(a){if(!sa){var b=P.createEventObject,c="complete"==P.readyState,d="interactive"==P.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){sa=!0;for(var e=0;e<ua.length;e++)ua[e]()}ua.push=function(){for(var a=0;a<arguments.length;a++)r(arguments[a]);return 0}}},wf=0,xf=function(){if(!sa&&140>wf){wf++;try{P.documentElement.doScroll("left"),vf()}catch(a){J.setTimeout(xf,50)}}},zf=function(a){var b=P.getElementById(a);if(b&&yf(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(yf(document.all[a][c],
"id")==a)return document.all[a][c];return b},yf=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Af=function(a){return a.target||a.srcElement||{}},xa=function(a){var b=P.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},Bf=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&
(e=null);return e},Cf=!1,Df=[],Ef=function(){if(!Cf){Cf=!0;for(var a=0;a<Df.length;a++)Df[a]()}},Ff=function(a){a=a||J;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},va=function(a){window.console&&window.console.log&&window.console.log(a)};var Gf=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||J.location.protocol.replace(":","")).toLowerCase();switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||J.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:J.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=f.split("/");0<=Xe(d||[],k[k.length-
1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var m=f.split("&"),l=0;l<m.length;l++){var n=m[l].split("=");if(decodeURIComponent(n[0]).replace(/\+/g," ")==e){f=decodeURIComponent(n.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Hf=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},ya=function(a){var b=P.createElement("a");
a&&(b.href=a);return b};var ga=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ba=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=Gf(ya(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};var ea=function(a,b){p("//bat.bing.com/bat.js",a,b)},u=J,da=function(a,b,c){b&&(void 0===u[a]||c&&!u[a])&&(u[a]=b);return u[a]},aa=function(a,b,c){return("https:"==J.location.protocol?a:b)+c};var If=new af,Jf={},Lf={set:function(a,b){Fa(Kf(a,b),Jf)},get:function(a){return C(a,2)},reset:function(){If=new af;Jf={}}},C=function(a,b){if(2==b){for(var c=Jf,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return If.get(a)},Kf=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Mf=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),Nf={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Of={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Pf=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Qf=function(){var a=C("gtm.whitelist");
var b=a&&Pf(Ze(a),Nf),c=C("gtm.blacklist")||C("tagTypeBlacklist")||[];Mf.test(J.location&&J.location.hostname)&&(c=Ze(c),c.push("nonGooglePixels","nonGoogleScripts"));var d=c&&Pf(Ze(c),Of),e={};return function(f){var g=f&&f[Ac];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)a:{if(0>Xe(b,g.a))if(g.b&&0<g.b.length)for(var k=0;k<g.b.length;k++){if(0>Xe(b,
g.b[k])){h=!1;break a}}else{h=!1;break a}h=!0}var m=!1;if(c){var l;if(!(l=0<=Xe(d,g.a)))a:{for(var n=g.b||[],q=new af,t=0;t<d.length;t++)q.set(d[t],!0);for(t=0;t<n.length;t++)if(q.get(n[t])){l=!0;break a}l=!1}m=l}return e[g.a]=!h||m}};var lf=function(a){var b=P;return Rf?b.querySelectorAll(a):null},Sf=!1;if(P.querySelectorAll)try{var Tf=P.querySelectorAll(":root");Tf&&1==Tf.length&&Tf[0]==P.documentElement&&(Sf=!0)}catch(a){}var Rf=Sf;var _eu=function(a){var b=String(C("gtm.elementUrl")||a[Xb]||""),c=ya(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return Ja};_e.a="e";_e.b=["google"];var Yf=/(^|\.)doubleclick\.net$/i,Zf=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,$f=function(a){for(var b=String(P.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=Ye(e[0]);if(f&&f==a){var g=Ye(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},ag=function(a,b,c,d,e){if(Yf.test(P.location.hostname)||"/"==c&&Zf.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=P.cookie;P.cookie=f;return g!=
P.cookie||0<=Xe($f(a),b)},bg=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},cg=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},dg=function(){var a=Gf(J.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var eg=function(a,b){this.f=a;this.j=b};eg.prototype.toString=function(){var a=""+this.f;1<this.j&&(a=a+"-"+this.j);return a};var fg=function(a,b){this.za=a;this.ba=b};fg.prototype.toString=function(){return""+this.ba+"."+this.za};var ig=function(a,b){var c=new gg(null,a,b);hg(c);return c},gg=function(a,b,c){this.Ga=Math.floor(K().getTime()/864E5);this.aa=b||"auto";this.T=c||"/";var d=bg(this.aa),e=cg(this.T);this.C=a||new eg(d,e);this.h=[];this.A=new af},kg=function(a,b,c){b&&(""==c.za?jg(a,b):(a.A.contains(b)||a.h.push(b),a.A.set(b,c)))},lg=function(a,b){for(var c=0;c<b.length;c++)kg(a,b[c][0],b[c][1])},jg=function(a,b){var c=Xe(a.h,b);0<=c&&a.h.splice(c,1);a.A.set(b,void 0)},mg=function(a){for(var b=[],c=0;c<a.h.length;c++){var d=
a.h[c];b.push([d,a.A.get(d)])}return b},ng=function(a){for(var b=0,c=0;c<a.h.length;c++)b=Math.max(b,a.A.get(a.h[c]).ba);return 864E5*b};gg.prototype.toString=function(){if(0==this.h.length)return"";for(var a=[],b=0;b<this.h.length;b++){var c=this.h[b];a.push(""+c+"."+this.A.get(c).toString())}return"GAX1."+this.C.toString()+"."+a.join("!")};
var og=function(a,b){for(var c=new Date,d=cg(a.T),e=[],f=0;f<a.h.length;f++){var g=a.h[f];a.A.get(g).ba<a.Ga&&e.push(g)}for(f=0;f<e.length;f++)jg(a,e[f]);if(a.h.length>(b||10))return!1;c.setTime(ng(a));if("auto"!=a.aa)return ag("_gaexp",a.toString(),a.T,a.aa,c);for(var h=dg(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.C=new eg(bg(h[k]),d),ag("_gaexp",a.toString(),a.T,h[k],c)))return!0;return!1},hg=function(a){for(var b=a.C.f,c=a.C.j,d=$f("_gaexp"),e=[],f=0;f<d.length;f++){var g=pg(a,d[f]);g&&e.push(g)}kf(e,
function(a,d){var e=a.C,f=d.C;return e.f==f.f&&e.j==f.j?!1:e.f==b&&e.j==c?!0:f.f==b&&f.j==c?!1:e.f==b?f.f!=b||e.j<f.j:f.f==b?!1:e.j==c?f.f!=b&&(f.j!=c||e.f<f.f):f.j==c?!1:e.f<f.f||e.f==f.f&&e.j<f.j});a.C=0<e.length?e[0].C:new eg(b,c);for(f=e.length-1;0<=f;f--)lg(a,mg(e[f]))},pg=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=Ye(e[0]);if(0!=f.length){var g=2==e.length?Ye(e[1]):"1";if(We(f)&&We(g)){d=new eg(N(f),N(g));
break a}}}d=void 0}if(d){for(var h=new gg(d,a.aa,a.T),k=(c[2]||"").split("!"),m=0;m<k.length;m++){var l=k[m].split(".");if(3==l.length){if(!We(l[1]))return;kg(h,l[0],new fg(l[2],N(l[1])))}}return h}}};var _v=function(a){var b=C(a[gd].replace(/\\\./g,"."),a[Pb]);return void 0!==b?b:a[Xb]};_v.a="v";_v.b=["google"];var _f=function(a){var b=String(C("gtm.referrer")||P.referrer);if(!b)return b;var c=ya(b);return b};_f.a="f";_f.b=["google"];var ia=function(a){var b=J.location,c;(c=a[Mb]?a[Mb]:C("gtm.url"))&&(b=ya(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[wb]&&(f=Gf(b,a[wb],a[Zd],a[Wb],a[Md]));return f},_u=ia;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[Xa])==String(a[R])};_eq.a="eq";_eq.b=["google"];var Dg=Math.random(),Eg="1.000000">Dg;var Fg=Ue;var Gg=Ue,Hg=[],Ig=!1,Jg=function(a){return J["googleTagManager"].push(a)},Kg=function(a){var b=!1;return function(){!b&&L(a)&&r(ef(a));b=!0}},Qg=function(){for(var a=!1;!Ig&&0<Hg.length;){Ig=!0;var b=Hg.shift();if(L(b))try{b.call(Lf)}catch(ta){}else if(U(b))a:{var c=b;if("string"==Da(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=Jf,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(ta){}}}else{var k=b,m=void 0;for(m in k)if(k.hasOwnProperty(m)){var l=m,n=
k[m];If.set(l,n);Fa(Kf(l,n),Jf)}var q=!1,t=k.event,v=void 0;if(t){v=ka++;Ja=t;if(!k["gtm.uniqueEventId"]){var x=v;If.set("gtm.uniqueEventId",x);Fa(Kf("gtm.uniqueEventId",x),Jf)}var z=Kg(k.eventCallback),E=k.eventTimeout;E&&J.setTimeout(z,Number(E));q=Gg(v,t,z,k.eventReporter)}Ia||(Ia=k["gtm.start"])&&Fg();var F=k,D=v,y=t,G=Jf;if(!q){var B=v,H=t;}Ja=null;a=q||a}var Q=b,M=Jf;Pg();Ig=!1}return!a};var Rg,Sg,Tg,Ug=/(Firefox\D28\D)/g.test(nf.userAgent),$g=function(a,b){return function(c){c=c||J.event;var d=Af(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=Bf(d,["a","area"]),e=!d||!d.href||Vg(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?Tg:Sg;if(c.defaultPrevented||!1===c.returnValue||c.oa&&c.oa()){if(d){var g={simulateDefault:!1},h=Wg(f,["wnc","nwnc"]);h&&Xg(a,d,g,f.wt,h)}}else{if(d){var g={},k,m=Wg(f,
["wnc","nwnc","nwc","wc"]);(k=Xg(a,d,g,f.wt,m))||(Yg(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&Ug;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=Zg(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},Xg=function(a,b,c,d,e){var f=d||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||yf(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event=
"gtm.linkClick";g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=ah(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=bh(b);g.eventTimeout=f;g.eventCallback=ch(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=(b.attributes&&b.attributes.formaction?b.formAction:"")||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return Jg(g)},
bh=function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},dh=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},Zg=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(nf.userAgent),e=dh(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=J.frames&&J.frames[f]||J[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName=
"gtm_autoEvent_"+K().getTime(),b.targetWindow=J.open("",b.targetWindowName));break;default:d&&!J.frames[e]?(b.simulateDefault=!1,c=!0):(J.frames[e]||(b.targetWindowName=e),b.targetWindow=J.frames[e]||J.open("",e))}return c},ah=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||K().getTime(),500>K().getTime()-c&&J.setTimeout(ah(a,b,c),25)))}},ch=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&
(d=a.target,a.target=b.targetWindowName);P.gtmSubmitFormNow=!0;eh(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||K().getTime(),500>K().getTime()-c&&J.setTimeout(ch(a,b,c),25)}},Wg=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},fh=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},Yg=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;
for(var c=0;c<gh.length;c++)if(a.passingRules[c]){var d=gh[c],e=hh[c],f=e&&e[0]&&e[0][0]||e[1]&&e[1][0];if(f&&"0"!=f&&(b.wc[f]||b.wnc[f]))for(var g=d[1],h=0;h<g.length;h++)if(a.resolvedTags[g[h]])return!0}return!1},ih=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(P.gtmHasClickListenerTag)return;P.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=Af(a);b&&Xg("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!Rg&&(Rg=Hf(P.location));fh(Sg,b||!1,c||!1,d,e);if(P.gtmHasLinkClickListenerTag)return;
P.gtmHasLinkClickListenerTag=!0;f="click";g=$g(a,b||!1);break;case "FORM_SUBMIT":fh(Tg,b||!1,c||!1,d,e);if(P.gtmHasFormSubmitListenerTag)return;P.gtmHasFormSubmitListenerTag=!0;f="submit";g=$g(a,b||!1);break;default:return}V(P,f,g,h)},Vg=function(a){if(!Rg)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=ya(a);return Rg==Hf(c)},eh=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
P.gtmFormElementSubmitter||(P.gtmFormElementSubmitter=P.createElement("form"));return P.gtmFormElementSubmitter.submit.call?P.gtmFormElementSubmitter.submit:a.submit};var qg=new String("undefined"),qh=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===qg?b:a[d]);return c.join("")}};qh.prototype.toString=function(){return this.resolve("undefined")};qh.prototype.valueOf=qh.prototype.toString;var rh={},sh=function(a,b){var c=ka++;rh[c]=[a,b];return c},th=function(a){var b=a?0:1;return function(a){var d=rh[a];if(d&&L(d[b]))d[b]();rh[a]=void 0}};var uh=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},vh=function(a,b){return a<b?-1:a>b?1:0};var wh;a:{var xh=za.navigator;if(xh){var yh=xh.userAgent;if(yh){wh=yh;break a}}wh=""}var X=function(a){return-1!=wh.indexOf(a)};var zh=X("Opera"),Ah=X("Trident")||X("MSIE"),Bh=X("Edge"),Ch;if(Ch=X("Gecko"))Ch=!(-1!=wh.toLowerCase().indexOf("webkit")&&!X("Edge"));var Dh=Ch&&!(X("Trident")||X("MSIE"))&&!X("Edge"),Eh=-1!=wh.toLowerCase().indexOf("webkit")&&!X("Edge");Eh&&X("Mobile");X("Macintosh");X("Windows");X("Linux")||X("CrOS");var Fh=za.navigator||null;Fh&&(Fh.appVersion||"").indexOf("X11");X("Android");!X("iPhone")||X("iPod")||X("iPad");X("iPad");X("iPod");
var Gh=function(){var a=za.document;return a?a.documentMode:void 0},Hh;a:{var Ih="",Jh=function(){var a=wh;if(Dh)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Bh)return/Edge\/([\d\.]+)/.exec(a);if(Ah)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Eh)return/WebKit\/(\S+)/.exec(a);if(zh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Jh&&(Ih=Jh?Jh[1]:"");if(Ah){var Kh=Gh();if(null!=Kh&&Kh>parseFloat(Ih)){Hh=String(Kh);break a}}Hh=Ih}
var Lh=Hh,Mh={},Nh=function(a){var b;if(!(b=Mh[a])){for(var c=0,d=uh(String(Lh)).split("."),e=uh(String(a)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var h=d[g]||"",k=e[g]||"",m=RegExp("(\\d*)(\\D*)","g"),l=RegExp("(\\d*)(\\D*)","g");do{var n=m.exec(h)||["","",""],q=l.exec(k)||["","",""];if(0==n[0].length&&0==q[0].length)break;c=vh(0==n[1].length?0:parseInt(n[1],10),0==q[1].length?0:parseInt(q[1],10))||vh(0==n[2].length,0==q[2].length)||vh(n[2],q[2])}while(0==c)}b=Mh[a]=0<=c}return b},
Oh=za.document,Ph=Oh&&Ah?Gh()||("CSS1Compat"==Oh.compatMode?parseInt(Lh,10):5):void 0;var Qh;if(!(Qh=!Dh&&!Ah)){var Rh;if(Rh=Ah)Rh=9<=Number(Ph);Qh=Rh}Qh||Dh&&Nh("1.9.1");Ah&&Nh("9");var Sh=function(a){Sh[" "](a);return a};Sh[" "]=function(){};var wa=function(a,b){var c="";Ah&&!Th(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(Uh)a.srcdoc=d;else if(Vh){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else Wh(a,d)},Uh=Eh&&"srcdoc"in document.createElement("iframe"),Vh=Dh||Eh||Ah&&Nh(11),Wh=function(a,b){Ah&&Nh(7)&&!Nh(10)&&6>Xh()&&Yh(b)&&(b=Zh(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};Ah&&!Th(a)?$h(a,c):c()},Xh=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},Th=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{Sh(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},ai=0,$h=function(a,b){var c="goog_rendering_callback"+ai++;window[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},Yh=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},Zh=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var ci=function(a,b,c,d){return function(){try{if(0<b.length){var e=b.shift(),f=ci(a,b,c,d);if("SCRIPT"==String(e.nodeName).toUpperCase()&&"text/gtmscript"==e.type){var g=P.createElement("script");g.async=!1;g.type="text/javascript";g.id=e.id;g.text=e.text||e.textContent||e.innerHTML||"";e.charset&&(g.charset=e.charset);var h=e.getAttribute("data-gtmsrc");h&&(g.src=h,pa(g,f));a.insertBefore(g,null);h||f()}else if(e.innerHTML&&0<=e.innerHTML.toLowerCase().indexOf("<script")){for(var k=[];e.firstChild;)k.push(e.removeChild(e.firstChild));
a.insertBefore(e,null);ci(e,k,f,d)()}else a.insertBefore(e,null),f()}else c()}catch(m){r(d)}}};var ei=function(a,b,c){if(P.body){var d=
a[Gc];d instanceof qh&&(d=d.resolve(sh(b,c)),b=Ue);if(a[Je])try{wa(ha(),"<script>var google_tag_manager=parent.google_tag_manager;\x3c/script>"+d),r(b)}catch(e){r(c)}else a[Le]?di(d,b,c):ci(P.body,xa(d),b,c)()}else J.setTimeout(function(){ei(a,b,c)},200)},_html=ei;_html.a="html";_html.b=["customScripts"];
var qi=function(a,b,c,d){var e=b+": "+c+(d?" !important":""),f=document;if(f.createStyleSheet){var g=ni(f),h=g.rules.length;g.addRule(a,e);return function(){g.removeRule?g.removeRule(h):g.deleteRule(h);g.addRule("x","-",h)}}var k=oi(a+"{"+e+"}",f);pi(k,f);var m=k.parentNode;return function(){m.removeChild(k)}},ri=null,ni=function(a){if(ri)return ri;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return ri=c}0==a.styleSheets.length&&
a.createStyleSheet();return ri=a.styleSheets[0]},oi=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},pi=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var yi={},zi=void 0,Ai=function(a){var b=yi[a];b||(b={id:a,s:[],O:0,Ba:null,ua:void 0,ya:!1},yi[a]=b);zi=b},Ci=function(a,b,c,d){var e=zi;if(!Rf||!e)return!1;var f={id:e.id+":"+e.s.length,Va:b,M:[],Qa:c,D:a,ma:0,ja:d||null,Fa:0,N:!1};e.s.push(f);null===a?(f.N=!0,b(null)):Bi(e);return!0},Di=function(a){var b=qi(a,"visibility","hidden",!0);return function(){L(b)&&b.apply();b=null}},Ei=function(a,b,c,d){var e=b;if(!sa){var f=Di(a.v);ua.push(f);e=function(a,c){var d=b(a,c);f();return d}}return Ci(a,e,
c,d)},Bi=function(a){if(!a.ya){for(var b=a.O;b<a.s.length;b++){var c=a.s[b],d=b==a.O;if(!c.N&&!Fi(d,c))break;c.N&&d&&a.O++}a.s.length>a.O?(a.Ba||(a.Ba=J.setTimeout(function(){a.Ba=null;Bi(a)},80)),sa||a.ua||(a.ua=function(){r(function(){Bi(a)})},V(P,"DOMContentLoaded",a.ua))):Gi(a)}},Gi=function(a){for(var b=0;b<a.s.length;b++){var c=a.s[b];if(c.D)for(var d=lf(c.D.v)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(Hi(f,c.id),c.M.push(Ii(f,c.id)))}}},Fi=
function(a,b){var c=[];if(b.D){var d=Ji(b.D,b.id),e=null;b.ja&&(e=Ji(b.ja,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!sa&&(null===b.ja.o||b.Fa+c.length<b.ja.o)))break;c.push({element:g,vb:h})}}if(!sa&&b.Qa&&(!a||null==b.D.o||b.D.o!=b.ma+c.length))return!1;for(var k=0;k<c.length;k++){var m=c[k].element,l=c[k].vb,n;b.ma++;Hi(m,b.id);l&&(b.Fa++,n=b.id+"-t",Hi(l,n));var q=b.Va(m,l);L(q)&&b.M.push(q);b.M.push(Ii(m,b.id));l&&n&&b.M.push(Ii(l,n))}if(b.D.o&&
b.D.o==b.ma||sa)b.N=!0;return!0},Hi=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},Ii=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},Ji=function(a,b){for(var c=lf(a.v)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.B&&!Ki(f))break;d.push(f)}}return d},Ki=function(a){if(sa)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var Ni,Oi;var Yi=function(a){return function(){}},Zi=function(a){return function(){}};var zj=function(a){var b=J||za,c=b.onerror,d=!1;Eh&&!Nh("535.3")&&(d=!d);b.onerror=function(b,f,g,h,k){c&&c(b,f,g,h,k);a({message:b,fileName:f,ob:g,Lb:h,error:k});return d}};
var Y=[],Bj={"\x00":"&#0;",'"':"&quot;","&":"&amp;","'":"&#39;","<":"&lt;",">":"&gt;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;","-":"&#45;","/":"&#47;","=":"&#61;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"},Cj=function(a){return Bj[a]},Dj=/[\x00\x22\x26\x27\x3c\x3e]/g;var Hj=/[\x00\x08-\x0d\x22\x26\x27\/\x3c-\x3e\\\x85\u2028\u2029]/g,Ij={"\x00":"\\x00","\b":"\\x08","\t":"\\t","\n":"\\n","\x0B":"\\x0b","\f":"\\f",
"\r":"\\r",'"':"\\x22","&":"\\x26","'":"\\x27","/":"\\/","<":"\\x3c","=":"\\x3d",">":"\\x3e","\\":"\\\\","\u0085":"\\x85","\u2028":"\\u2028","\u2029":"\\u2029",$:"\\x24","(":"\\x28",")":"\\x29","*":"\\x2a","+":"\\x2b",",":"\\x2c","-":"\\x2d",".":"\\x2e",":":"\\x3a","?":"\\x3f","[":"\\x5b","]":"\\x5d","^":"\\x5e","{":"\\x7b","|":"\\x7c","}":"\\x7d"},Jj=function(a){return Ij[a]};Y[7]=function(a){return String(a).replace(Hj,Jj)};
Y[8]=function(a){if(null==a)return" null ";switch(typeof a){case "boolean":case "number":return" "+a+" ";default:return"'"+String(String(a)).replace(Hj,Jj)+"'"}};
var Rj=/[\x00- \x22\x27-\x29\x3c\x3e\\\x7b\x7d\x7f\x85\xa0\u2028\u2029\uff01\uff03\uff04\uff06-\uff0c\uff0f\uff1a\uff1b\uff1d\uff1f\uff20\uff3b\uff3d]/g,Sj={"\x00":"%00","\u0001":"%01","\u0002":"%02","\u0003":"%03","\u0004":"%04","\u0005":"%05","\u0006":"%06","\u0007":"%07","\b":"%08","\t":"%09","\n":"%0A","\x0B":"%0B","\f":"%0C","\r":"%0D","\u000e":"%0E","\u000f":"%0F","\u0010":"%10","\u0011":"%11","\u0012":"%12","\u0013":"%13",
"\u0014":"%14","\u0015":"%15","\u0016":"%16","\u0017":"%17","\u0018":"%18","\u0019":"%19","\u001a":"%1A","\u001b":"%1B","\u001c":"%1C","\u001d":"%1D","\u001e":"%1E","\u001f":"%1F"," ":"%20",'"':"%22","'":"%27","(":"%28",")":"%29","<":"%3C",">":"%3E","\\":"%5C","{":"%7B","}":"%7D","\u007f":"%7F","\u0085":"%C2%85","\u00a0":"%C2%A0","\u2028":"%E2%80%A8","\u2029":"%E2%80%A9","\uff01":"%EF%BC%81","\uff03":"%EF%BC%83","\uff04":"%EF%BC%84","\uff06":"%EF%BC%86","\uff07":"%EF%BC%87","\uff08":"%EF%BC%88","\uff09":"%EF%BC%89",
"\uff0a":"%EF%BC%8A","\uff0b":"%EF%BC%8B","\uff0c":"%EF%BC%8C","\uff0f":"%EF%BC%8F","\uff1a":"%EF%BC%9A","\uff1b":"%EF%BC%9B","\uff1d":"%EF%BC%9D","\uff1f":"%EF%BC%9F","\uff20":"%EF%BC%A0","\uff3b":"%EF%BC%BB","\uff3d":"%EF%BC%BD"},Tj=function(a){return Sj[a]};Y[16]=function(a){return a};var Vj=36,Wj=[],Xj=[],Yj=[],Zj=new af,ak=[],Z=[],gh=[],hh=[],bk=function(){this.G=[]};bk.prototype.set=function(a,b){this.G.push([a,b]);return this};bk.prototype.resolve=function(a,b){for(var c={},d=0;d<this.G.length;d++){var e=ck(this.G[d][0],a,b),f=ck(this.G[d][1],a,b);c[e]=f}return c};var dk=function(a){this.index=a};dk.prototype.resolve=function(a,b){var c=Yj[this.index];if(c&&!b(c)){var d=c[Lc];if(a){if(a.get(d))return;a.set(d,!0)}c=ck(c,a,b);a&&a.set(d,!1);return bf(c)}};
var _M=function(a){return new dk(a)},ek=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=ck(Wj[a[f]],b,c);g===qg&&(e=!0);d.push(g)}return e?new qh(d):d.join("")}},_T=function(a){return new ek(arguments)},fk=function(a){function b(b){for(var d=1;d<a.length;d++)if(a[d]==b)return!0;return!1}this.resolve=
function(c,d){var e=ck(a[0],c,d);if(a[0]instanceof dk&&b(8)&&b(16)){if(e===qg)return e;var f="gtm"+ka++;Zj.set(f,e);return'google_tag_manager["GTM-NDJTNB"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=Y[a[g]](e);return e}},_E=function(a,b){return new fk(arguments)},gk=function(a,b){this.u=a;this.ia=b},_R=function(a,b){return new gk(a,b)},hk=function(a,b){return ck(a,new af,b)},ck=function(a,b,c){var d=a;if(a instanceof dk||a instanceof bk||a instanceof ek||a instanceof fk)return a.resolve(b,
c);if(!(a instanceof gk))if(U(a))for(var d=[],e=0;e<a.length;e++)d[e]=ck(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=ck(a[f],b,c))}return d},ik=function(a,b){var c=b[a],d=c;if(c instanceof dk||c instanceof fk||c instanceof ek||c instanceof gk)d=c;else if(U(c))for(var d=[],e=0;e<c.length;e++)d[e]=ik(c[e],b);else if("object"==typeof c){var d=new bk,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],ik(c[f],b))}return d},kk=function(a,b){for(var c=b?b.split(","):
[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=Wj[e[1]]);if(1==a)for(var f=jk(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=Xj[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=jk(e[g]);3==a&&(c[d]=Wj[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=Wj[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},jk=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<Vj;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=
e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},lk=function(a,b,c){a.push.apply(a,kk(b,c))};
var Mg=function(){},tk=function(a){},Pg=function(){},uk=function(a){},vk=function(a,b){},wk=function(a,b){},Ng=function(a){};var xk=function(a){var b=this;this.g=a;this.complete=this.Na=!1;this.ha=[];this.ca=[];this.S=function(){if(b.i&&b.i.event){var a=b.i.event,d=b.g;}b.complete||ff(b.ha);jf(b,1)};this.R=function(){if(b.i&&b.i.event){var a=b.i.event,d=b.g;}b.complete||ff(b.ca);jf(b,2)};this.w=Ue},yk=function(a,b){a.ha.push(b)},
zk=function(a,b){a.ca.push(b)},Ak=function(a){this.H=[];this.Aa=[];this.Ha={};this.sa=[];this.P=0;this.La={};this.Oa={};this.ka={};this.event=a};Ak.prototype.addListener=function(a){this.sa.push(a)};
var Bk=function(a,b,c,d,e,f){if(!c.complete){a.H[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=U(d)?d.slice():["or",d];e=U(e)?e.slice():[e];f=U(f)?f.slice():[f];a.Ha[b]=d;a.La[b]=0<e.length;a.Oa[b]=0<f.length;a.P++;var g=function(){0<a.P&&a.P--;0<a.P||ff(a.sa)};yk(c,g);zk(c,g)}},Ck=function(a,b,c){a.H[b]&&(yk(a.H[b],function(){c(b,!0)}),zk(a.H[b],function(){c(b,!1)}))},Dk=function(a,b){var c=!1;return function(d,e){var f;a:{for(var g=0;g<a.length;g++)if(a[g]instanceof gk&&a[g].u===
d||a[g]===d){f=g;break a}f=-1}c||0>f||("or"==a[0]?e?(c=!0,b()):(a.splice(f,1),1==a.length&&(c=!0)):e?(a.splice(f,1),1==a.length&&(c=!0,b())):c=!0)}},Hk=function(a,b){var c=[],d=!1,e=function(b){var f,g,h=Z[b];if(a.event.c(h)){}else g=Ek(h,b,a);if(f=g){var k=Fk(b,!0);0<k.length&&e(k[0].u);c.push(f);var l=Fk(b,!1);0<l.length&&e(l[0].u)}else d=
!0};e(b);if(!d){for(var f=0;f<c.length;f++){var g=c[f],h=Fk(g.g,!0);if(0<h.length){var k=c[f-1],m=Gk(g);yk(k,m);0==h[0].ia&&zk(k,m)}var l=Fk(g.g,!1);0<l.length&&(m=Gk(c[f+1]),yk(g,m),0==l[0].ia&&zk(g,m))}a.Aa.push(c)}},Fk=function(a,b){var c=b?Wd:me,d=Z[a],e=void 0===d[c]?[]:d[c];return U(e)?e:[e]},Gk=function(a){return function(){a.w()}},Jk=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Fk(a,!0);0<b.length&&f(b[0].u);e.push(a);var c=Fk(a,!1);0<c.length&&f(c[0].u)};
f(d.g);b[d.g]=e}Ik(a,b);return b},Ik=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].g,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<Xe(b[e],d)){delete b[d];break}}};var Lk=function(a,b){return function(){a[Cc]=b.S;a[Dc]=b.R;var c=b.g,d=b.i&&b.i.ka[c],e=Ka[c]&&Ka[c].state,f=d?void 0!==d:b.Na,g=Ka[c]&&Ka[c].firingOption,h=g&&2==g,k=g&&1==g;if((f||e&&0!=e)&&(f||h)&&(h||k))h&&Ka[c]&&1==Ka[c].state||k&&b.i&&1==b.i.ka[c]?b.S():b.R();else{var m=b.i?b.i.event:void 0;a=Kk(a,m?m.c:Qf());jf(b,0);if(m){var l=a;vk(m,c)}bf(a,b.S,b.R)}}},Kk=function(a,b){a=hk(a,b);return a},Ek=function(a,b,c){var d=new xk(b);d.i=c;yk(d,Yi(a));zk(d,Zi(a));d.w=Lk(a,d);return d};var Qk,Rk;var $k=!1;var al=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=ak[b]&&hk(ak[b],c),e=d;if(d)if(d[Wa]&&U(d[R]))for(var f=d[R],e=!1,g=0;!e&&g<f.length;g++)d[R]=f[g],e=bf(d);else e=bf(d);a[b]=[e,d]}return a[b]}},sk=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.K(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.K(e[d],a.c)[0])return!1;return!0},bl=!1,Gg=function(a,b,c,d){switch(b){case "gtm.js":if(bl)return!1;bl=!0;break;case "gtm.sync":if(C("gtm.snippet")!=Ha)return!1}C("tagTypeBlacklist");
for(var e={id:a,name:b,Y:c||Ue,X:jk(),ga:jk(),K:al(),c:Qf()},f=[],g=0;g<gh.length;g++)if(sk(e,gh[g])){f[g]=!0;for(var h=e,k=gh[g],m=k[1],l=0;l<m.length;l++)h.X[m[l]]=!0;for(var n=k[3],l=0;l<n.length;l++)h.ga[n[l]]=!0}else f[g]=!1;vk(e);var t=[];for(var v=0;v<Vj;v++)if(e.X[v]&&!e.ga[v])if(e.c(Z[v])){}else{t[v]=Z[v];}e.L=t;for(var x=new Ak(e),z=0;z<Vj;z++)if(e.X[z]&&!e.ga[z])if(e.c(Z[z])){}else{var E=e.L[z],F=Ek(E,z,x);Bk(x,z,F,E[Yb],E[Wd],E[me]);if(E[La])break}x.addListener(e.Y);for(var D=[],y=
0;y<x.H.length;y++){var G=x.H[y];if(G){var w=x.Ha[y],B=x.La[y],H=x.Oa[y];if(0!=w.length||B||H){if(0<w.length)for(var Q=Dk(w,G.w),M=0;M<w.length;M++)w[M]instanceof gk&&w[M].u!=y&&Ck(x,w[M].u,Q);(B||H)&&Hk(x,y)}else D.push(y)}}for(y=0;y<D.length;y++)x.H[D[y]].w();for(y=0;y<x.Aa.length;y++){for(var ta=x.Aa[y],T=ta,fa=[],ca=0;ca<T.length;ca++){var kb=T[ca],ib=kb.g,Hb=Ka[ib],md=Hb.firingOption;0!=md&&(1==md&&void 0!==kb.i.ka[ib]||2==md&&void 0!==Hb.state)&&fa.push(kb)}var nd=Jk(fa),oc=void 0;for(oc in nd)if(nd.hasOwnProperty(oc)){for(var of=
void 0,ej=void 0,id=nd[oc],ol=id[0],lj=id[id.length-1],mj,Ga=0;Ga<T.length;Ga++){var jd=T[Ga];!of&&jd.g==ol&&0<Ga&&(of=T[Ga-1]);jd.g==lj&&Ga<T.length-1&&(ej=T[Ga+1]);if(-1<Xe(id,jd.g))if(mj=T.splice(Ga,1)[0],jd.g==lj)break;else Ga--}if(mj){var nj=Number(oc),ja=of,pf=ej;if(ja){var pl=ja.ha[0],ql=ja.ca[0],oj=ja;oj.ha=[];oj.ca=[];yk(ja,pl);zk(ja,ql)}if(ja&&pf){var qf=Gk(pf);yk(ja,qf);var rf=Fk(ja.g,!1);0<rf.length&&rf[0].u!=nj&&0==rf[0].ia&&zk(ja,qf);var sf=Fk(pf.g,!0);0<sf.length&&sf[0].u!=nj&&0==sf[0].ia&&
zk(ja,qf)}}}0<ta.length&&ta[0].w()}0<x.P||ff(x.sa);d&&L(d)&&d({passingRules:f,resolvedTags:e.L});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var rj in e.L)if(e.L.hasOwnProperty(rj)){var sj=e.L[rj],tf;if(!(tf=void 0==sj[Lc])){var tj=sj[Lc];tf=!("function"!=typeof String.prototype.startsWith?0===tj.indexOf("_implicit"):tj.startsWith("_implicit"))}if(tf)return!0}return!1};var cl={macro:function(a){if(Zj.contains(a))return Zj.get(a)}};cl.dataLayer=Lf;cl.onHtmlSuccess=th(!0);cl.onHtmlFailure=th(!1);cl.Za=function(){var a=J.google_tag_manager;a||(a=J.google_tag_manager={});a["GTM-NDJTNB"]||(a["GTM-NDJTNB"]=cl);qa=a};(function(){var a=function(a){var c=I("google_tag_manager",{},!1),d=c[a];d||(d=c[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};Sg=a("linkClickMap");Tg=a("formSubmitMap")})();
Wj.push.apply(Wj,function(){for(var a=[_eq,_e,'_event',_M(0),'gtm.js','1429170_2147479553',_html,true,'\x3cscript type\x3d\x22text/gtmscript\x22\x3evar img\x3ddocument.createElement(\x22img\x22),url\x3d\x22',_v,'url',2,_E(_M(1),7),'\x22;img.src\x3d\x22//sb.scorecardresearch.com/p?c1\\x3d2\\x26c2\\x3d20632726\\x26cv\\x3d2.0\\x26cj\\x3d1\\x26c7\\x3d\x22+url+\x22\\x26c4\\x3d\x22+url;\x3c/script\x3e',_T(8,12,13),'fire-pixels','pixels','1429170_7','\x3cscript type\x3d\x22text/gtmscript\x22\x3efor(var pixels\x3d',_E(_M(2),8,16),',i\x3d0;i\x3cpixels.length;i++){var pixel\x3dpixels[i],img\x3dnew Image;img.src\x3dpixel};\x3c/script\x3e',_T(18,19,20),5,'\x3cscript type\x3d\x22text/gtmscript\x22\x3e','userMatching','',_E(_M(3),8,16),'\x26\x26r.frames.postMessage(window.parent,\x22userMatched.gtm\x22);\x3c/script\x3e',_T(23,26,27),6,'subreddit','origin',_u,'Page URL','Page Hostname','host','Page Path','path',_f,'Referrer','Event'],b=[],c=0;c<a.length;c++)b[c]=ik(c,a);return b}());lk(Xj,0,"5:0,5:1,7:2,0:3,1:4,5:6,9:7,5:9,7:10,8:10,3:11,6:14,10:11,1:15,7:16,8:16,6:21,10:22,7:24,8:24,4:25,6:28,10:29,7:30,8:30,7:31,8:31,5:32,7:33,7:34,2:35,7:36,2:37,5:38,7:39,7:40");lk(Yj,1,"G,Ae,ASM,ASAH,ASAgB,ASAAG,AAAAY,AAAAoB,AAAAIG,AAAAAY,CAAAAg");lk(ak,1,"Z,JAC");lk(Z,1,"ghB,gBw,gBAY");lk(gh,2,"B:F::,C:C::");lk(hh,4,"5.5:,17:");for(var dl=0;dl<Z.length;dl++){var el=Z[dl],fl=1;el[rd]?fl=2:el[Fe]&&(fl=0);Ka[dl]={firingOption:fl,state:void 0}}cl.Za();
(function(a){})("async");
(function(){var a=I("googleTagManager",[],!1),b=I("google_tag_manager",{},!1),b=b["googleTagManager"]=b["googleTagManager"]||{};ua.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Df.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Hg.push.apply(Hg,b);300<this.length;)this.shift();return Qg()};Hg.push.apply(Hg,a.slice(0));r(Qg)})();
if("interactive"==P.readyState&&!P.createEventObject||"complete"==P.readyState)vf();else{V(P,"DOMContentLoaded",vf);V(P,"readystatechange",vf);if(P.createEventObject&&P.documentElement.doScroll){var nl=!0;try{nl=!J.frameElement}catch(a){}nl&&xf()}V(J,"load",vf)}"complete"===P.readyState?Ef():V(J,"load",Ef);
(function(a){})("async");(function(){})();var _vs="res_ts:1461779033949000,srv_cl:123464597,ds:live,cv:16";
})()
